
DROP TABLE MYMEMBER;

CREATE TABLE MYMEMBER(
M_ID VARCHAR2(250) NOT NULL,
M_NICK VARCHAR2(250) NOT NULL,
M_PASS VARCHAR2(250) NOT NULL,
M_NAME VARCHAR2(250) NOT NULL,
M_EMAIL VARCHAR2(300) NOT NULL,
M_PHONE VARCHAR2(300) NOT NULL,
M_FLAG VARCHAR2(2) NOT NULL,
M_GRADE VARCHAR2(100) NOT NULL,

CONSTRAINT MYMEMBER_PK PRIMARY KEY (M_ID),
CONSTRAINT MYMEMBER_UQ_NICK UNIQUE (M_NICK),
CONSTRAINT MYMEMBER_UQ_PHONE UNIQUE (M_PHONE),
CONSTRAINT MYMEMBER_UQ_EMAIL UNIQUE (M_EMAIL),
CONSTRAINT MYMEMBER_CHK_ENABLED CHECK(M_FLAG IN ('Y', 'N'))
);


INSERT INTO M_MEMBER VALUES
('kei01118','george', 'cmj7423', '조민지', 'kei01118@naver.com', '01037248165',
'Y', 'user');
INSERT INTO M_MEMBER VALUES
'KIM','babo', '1234', '김동주', 'djkim1216@naver.com', '01071817380',
'Y', 'user');

SELECT * FROM MYMEMBER;













